### ISSUE TITLE
App crash when trying to accces to /user/"username"/expressions when not logged

### ISSUE THREAD

**Issue by NanezX** [rainprotocol/rain-studio#30]
This happened to me when the session end meanwhile I was checking expressions dashbord.

The app crash with an `500 Internal Error` with this on the server side:

```
Invalid "number" argument: NaN
RangeError: Invalid "number" argument: NaN
    at parseNumber (/home/nanez/terra-virtua/rain-studio/node_modules/relative-time-format/commonjs/RelativeTimeFormat.js:455:13)
    at parseFormatArgs (/home/nanez/terra-virtua/rain-studio/node_modules/relative-time-format/commonjs/RelativeTimeFormat.js:485:11)
    at RelativeTimeFormat.format (/home/nanez/terra-virtua/rain-studio/node_modules/relative-time-format/commonjs/RelativeTimeFormat.js:160:30)
    at TimeAgo.formatDateForStep (/home/nanez/terra-virtua/rain-studio/node_modules/javascript-time-ago/commonjs/TimeAgo.js:337:48)
    at TimeAgo.format (/home/nanez/terra-virtua/rain-studio/node_modules/javascript-time-ago/commonjs/TimeAgo.js:233:32)
    at TimeAgo.svelte:14:27
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/lib/expressions/ExpressionRow.svelte:25:88)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1876:22)
    at eval (/src/lib/expressions/DeployedExpressionSummaryRow.svelte:45:108)
```

To reproduce this error, as I said before, just logout and tried to access to any user expressions dashbourd like `/user/nanezx/expressions` and the app will crash.

**Comment by thedavidmeister** [comment]
Re-verified against main 2026-07-04: still present — repository last updated 2023-08-31; the expressions route crash when not authenticated appears unresolved per last commit inspection. (automated verification note)

**Comment by thedavidmeister** [comment]
Closing: repo archived 2026-07-05 — rain-studio has been frozen since August 2023; open items lapse with it.
